feat: add upsert object handler
supabase/storage-api pull request #31
Opened 2021-06-15 17:01 UTC by ankitjena

## What kind of change does this PR introduce?

Feature

## What is the current behavior?

The create object handler throws duplicate not allowed error, if object already exists

## What is the new behavior?

Adds route
```
POST /object/upsert/:bucketName/*
```
which inserts an object if it doesn't exist. If it does exist it updates the object with new file.

### Screen recording
![Peek 2021-06-15 22-23](https://user-images.githubusercontent.com/23580602/122094034-4e71e480-ce29-11eb-991f-9c11ed231f91.gif)

2021-06-16 04:39 UTC, inian requested changes

2021-06-16 04:39 UTC, inian commented on src/routes/object/upsertObject.ts
> +      const objectResponse = await postgrest
Can you use the [upsert function](https://supabase.io/docs/reference/javascript/upsert) of postgrest? Saves us a API call

2021-06-16 05:28 UTC, inian commented
Hi Ankit, thank you so much for the PR! Looking at the code, once you use the `upsert` call of postgrest-js, the code will be almost exactly the same as `createObject`. 

What do you think about adding upsert functionality into createObject itself? By default, we won't upsert but if there is a header called `x-upsert: true`, we upsert instead of insert. 

Another advantage of this, we wont need to create a [new API endpoint](https://github.com/supabase/storage-api/pull/31/files#diff-0c165bea0a64be46e0ee17e68fa7ff006cb57e7b69b5dabb62ff23ac14bdc524R41). The API endpoint `/upsert/:bucketName/*` will probably clash with the current endpoint if the user has a bucket name called `upsert` which is a problem

2021-06-16 05:57 UTC, ankitjena commented
Right, I was thinking of the same thing about having upsert inside `createObject`, having a discussion on that would have been better I guess. Also I didn't think of the clash with bucketName for the upsert endpoint. Thanks Inian. I will work on that and make the changes.

2021-06-16 05:59 UTC, inian commented
Thanks Ankit :)

> I didn't think of the clash with bucketName for the upsert endpoint.

I learnt this the hard way as well haha https://github.com/supabase/storage-api/issues/22

2021-06-16 06:04 UTC, inian commented
Also can you merge in the changes from master Ankit? I just made some changes to the createObject file.

2021-06-16 09:04 UTC, ankitjena commented
> Also can you merge in the changes from master Ankit? I just made some changes to the createObject file.

Sure.

@inian I was trying the upsert now, for some reason it doesn't work, looked up the documentation in postgrest-js
![image](https://user-images.githubusercontent.com/23580602/122190799-c71b8400-ceaf-11eb-98e1-3f2d804d2654.png)
```
const { data: results, error, status } = await postgrest
        .from<Obj>('objects')
        .insert(
          [
            {
              name: objectName,
              owner: owner,
              bucket_id: bucketName,
            },
          ],
          {
            returning: 'minimal',
            upsert: true,
          }
        )
        .single()
```
I get the same error
```
{
  "statusCode": "23505",
  "error": "Key (bucket_id, name)=(avatars, folder/cat-new.png) already exists.",
  "message": "duplicate key value violates unique constraint \"bucketid_objname\""
}
```

2021-06-18 10:58 UTC, ankitjena commented
@inian Any suggestion for where I should look at for resolving this?

2021-06-20 05:53 UTC, ankitjena commented
Apparently, the postgrest client wasn't exposing the upsert method in query builder, I upgraded the package and using it worked. I was trying out the deprecated insert operation with upsert sadly.

2021-06-20 06:19 UTC, ankitjena commented
I messed up the merge somehow, closing this PR and creating another one.

2021-06-20 06:19 UTC, closed without merging